# Generated by Django 3.2.2 on 2024-07-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task2app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
