# Generated by Django 3.2.2 on 2024-07-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task2app', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userId',
        ),
    ]
