# Generated by Django 3.2.2 on 2024-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2app', '0003_auto_20240707_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='org_id',
            new_name='orgId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='isStaff',
        ),
        migrations.AddField(
            model_name='user',
            name='isSuperuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
