# Generated by Django 3.2.2 on 2024-07-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2app', '0004_auto_20240707_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isStaff',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isSuperuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
